name: CI/CD

on:
  pull_request:
    branches:
      - "*"

jobs:
  livraison_continue:
    runs-on: ubuntu-22.04
    env:
      IMAGE_NAME: "mynode:19"
    steps:
      uses: actions/checkout@v3
      - run: npm install
      - run: npm run lint
