name: CI/CD
on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
    - main
    tags:
      - "*"
jobs:
  livraison_continue:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout to current repository 
      uses: actions/checkout@v3
    - name: Set up PHP 8.1
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
    - name: Install dependencies
      run: composer install
    - name: Execute lint
      run: vendor/bin/phpcbf --standard=PSR2 ./src
    - name: Execute tests
      run: vendor/bin/phpunit
    - name: Execute docker build
      uses: docker/setup-buildx-action@v3
  deploiement_continue:
    runs-on: ubuntu-22.04
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && startsWith(github.event.after, 'refs/tags/'))
    needs: livraison_continue
    steps:
    - name: Checkout to current repository 
      uses: actions/checkout@v3
    - name: Get the tag name
      id: get_tag
      run: echo "TAG_NAME=$(echo ${GITHUB_REF#refs/tags/})" >> $GITHUB_ENV
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: moshtek
        password: ${{ secrets.DOCKERHUB_CI_CD }}
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        push: true
        context: ./
        tags: "moshtek/CI:${{ env.TAG_NAME }}"
