name: CI/CD
on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
    - main
jobs:
  livraison_continue:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout to current repository 
      uses: actions/checkout@v3
    - name: Set up PHP 8.1
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
    - name: Install dependencies
      run: composer install
    - name: Execute lint
      run: vendor/bin/phpcbf --standard=PSR2 ./src
    - name: Execute tests
      run: vendor/bin/phpunit
  docker_build_push:
    runs-on: ubuntu-22.04
    if: startsWith(github.ref, 'refs/tags/')
    steps:
    - name: Checkout to current repository 
      uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: moshtek
        password: ${{ secrets.DOCKERHUB_CI_CD }}
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        push: true
        context: ./
        tags: "moshtek/test"
