name: CI/CD
on:
  pull_request:
    branches:
      - "*"

jobs:
  livraison_continue:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout to current repository 
      uses: actions/checkout@v3
    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'
    - name: Install dependencies
      run: composer install
    - name: Execute lint
      run: vendor/bin/phpcbf --standard=PSR2 ./src